name: yugioh_scanner
description: "Yugidex - Advanced Yu-Gi-Oh! card scanner and collection manager with OCR technology."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # Make sure this matches your Flutter SDK version constraint if needed
  sdk: '>=3.0.0 <4.0.0' # Example constraint, adjust as necessary

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0 # Consider checking for newer versions
  google_mlkit_text_recognition: ^0.15.0 # Consider checking for newer versions
  http: ^1.2.0 # Consider checking for newer versions
  provider: ^6.1.2 # Consider checking for newer versions
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.5.0 # Consider checking for newer versions
  string_similarity: ^2.1.0
  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  lucide_icons: ^0.257.0 # Consider checking for newer versions
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2 # Consider checking for newer versions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # Consider checking for newer versions
  flutter_lints: ^5.0.0 # Consider checking for newer versions (e.g., ^4.0.0)

# --- CORRECTED LAUNCHER ICON CONFIGURATION ---
flutter_launcher_icons:
  android: true                 # Generate Android icons
  ios: true                     # Generate iOS icons
  image_path: "assets/icon/logo.png" # Path to your main 1024x1024 icon
  min_sdk_android: 21           # Optional: Ensure this matches your android/app/build.gradle minSdk
  # --- Optional: Settings for Android Adaptive Icons ---
  # adaptive_icon_background: "#0A192F" # Background color (e.g., your app's dark blue)
  # adaptive_icon_foreground: "assets/icon/icon_foreground.png" # Path to icon foreground layer (can have transparency)
  # --- End Optional ---
# --- END LAUNCHER ICON CONFIGURATION ---


flutter:
  uses-material-design: true

  # --- CORRECTED ASSET DECLARATIONS ---
  assets:
    - .env                     # Keep specific files like .env
    - packcodes/card_codes.txt # Keep specific data files if needed outside asset folders
    - assets/                  # Declare the entire assets folder
    - assets/images/           # Declare the images folder
  # --- END ASSET DECLARATIONS ---

  # --- Font configuration (if you add custom fonts) ---
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # --- End Font configuration ---